name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build_image:
    name: Build image, push image to DockerHub and ERC
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Build image
        run: docker build . -t stefan:latest

      - name: Log into ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
        
      - name: Log into DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        
      - name: Push image to ECR
        run: |
          rev=$(git rev-parse --short HEAD)
          docker tag stefan:latest 244530008913.dkr.ecr.eu-west-1.amazonaws.com/stna003:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/stna003:$rev
          
      - name: Push image to DockerHub
        run: |
          rev=$(git rev-parse --short HEAD)
          docker tag stefan:latest stefannaeve/stefan:$rev
          docker push stefannaeve/stefan:$rev
        
        