name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build_image:
    name: Build image, push image to DockerHub and ERC
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build image
        run: docker buildx build . -t stefan:latest
        
      - name: Upload image as artifact
        uses: ishworkh/container-image-artifact-upload@v2.0.0
        with:
          image: "stefan:latest"
          
  # push_to_ECR:
  #   name: Log into ECR and push image to ECR
  #   runs-on: ubuntu-latest
  #   needs: build_image
  #   steps:
  #     - name: Log into ECR
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       run: |
  #         aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
      
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: stefan
  #         path: stefan.tar
      
  #     - name: Load Docker image
  #       run: docker load -i ./stefan.tar
        
  #     - name: Push image to ECR
  #       run: |
  #         rev=$(git rev-parse --short HEAD)
  #         docker tag stefan:latest 244530008913.dkr.ecr.eu-west-1.amazonaws.com/stna003:$rev
  #         docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/stna003:$rev
      
  # push_to_dockerhub:
  #   name: Log into DockerHub and push image to DockerHub
  #   runs-on: ubuntu-latest
  #   needs: build_image
  #   steps:
  #     - name: Log into DockerHub
  #       uses: docker/login-action@v3
  #       with: 
  #         username: ${{secrets.DOCKERHUB_USERNAME}}
  #         password: ${{secrets.DOCKERHUB_PASSWORD}}
          
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: stefan
  #         path: stefan.tar
          
  #     - name: Load Docker image
  #       run: docker load -i ./stefan.tar
          
  #     - name: Push image to DockerHub
        # run: |
        #   rev=$(git rev-parse --short HEAD)
        #   docker tag stefan:latest stefannaeve/stefan:$rev
        #   docker push stefannaeve/stefan:$rev
        
        