name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          docker build . -t stefan
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push Docker image to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker tag stefan 244530008913.dkr.ecr.eu-west-1.amazonaws.com/stna003:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/stna003:$rev
  push_to_docker_hub:
    name: Push docker image to docker
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Log in
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      - name: Push image
        run: |
          rev=$(git rev-parse --short HEAD)
          docker tag stefan stefannaeve/stefan:$rev
          docker push stefannaeve/stefan:$rev
        
        